language: cpp

matrix:
    include:

        - name: "Linux gcc"
          os: linux
          dist: xenial
          compiler: gcc

        # - name: "Linux clang"
        #   os: linux
        #   dist: xenial
        #   compiler: clang

        # - name: "macOS Xcode 10 (Makefiles)"
        #   os: osx
        #   osx_image: xcode10
        #   env:
        #
        # - name: "Visual studio 15 2017"
        #   os: windows
        #   env:

before_script:
    - sudo apt-get install -y libxrandr-dev libxinerama-dev libx11-dev libcursor-dev libxi-dev libxext-dev

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
